config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to:'transactions#index'
  resources :transactions
  #get 'transactions', to: 'transactions#index'
  #get 'transactions/:id', to: 'transactions#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  enum transaction_type: { income: 0, outcome: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  def index
    @transactions = Transaction.all
  end

  def show; end

  def new
    @transaction = Transaction.new
  end

  def edit; end

  def create
    @transaction = Transaction.new(transaction_params)

    if @transaction.save
      redirect_to transaction_url(@transaction), notice: "Transaction was successfully created." 
    else
      render :new, status:  :unprocessable_entity 
    end
  end

  def update
    if @transaction.update(transaction_params)
      redirect_to transaction_url(@transaction), notice: "Transaction was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @transaction.destroy
    redirect_to transactions_path
  end

  private
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def transaction_params
      params.require(:transaction).permit(:transaction_type, :value, :description, :transaction_date, :status)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | App
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    = yield

app/views/transactions/_form.html.slim
= simple_form_for transaction do |f|
  = f.error_notification 
  = f.input :transaction_type, collection: Transaction.transaction_types.keys
  = f.input :value
  = f.input :description
  = f.input :transaction_date
  = f.input :status
  = f.error :base
  = f.button :submit

app/views/transactions/edit.html.slim
h1 
  | Editing Transactions 
= render 'form', transaction: @transaction
= link_to 'Back', transactions_path, class: "btn btn-sm fw-bold btn-secondary me-2 mb-2"

app/views/transactions/index.html.slim
#notice
  = notice

h1
  | Finance

table 
  thead 
    tr 
      th 
        = @transactions.human_attribute_name(:transaction_type)
      th 
         = @transactions.human_attribute_name(:value)
      th
         = @transactions.human_attribute_name(:description)
      th 
         = @transactions.human_attribute_name(:transaction_date)
      th 
         = @transactions.human_attribute_name(:status)

      th[colspan="5"]

  tbody
    - @transactions.each do |transaction|
      tr
        td
          = transaction.transaction_type 
        td 
          = transaction.value 
        td 
          = transaction.description
        td 
          = transaction.transaction_date 
        td 
          = transaction.status
        td 
          = link_to 'Show', transaction_path(transaction), class: "btn btn-sm fw-bold btn-secondary me-2 mb-2"
          = link_to 'Edit', edit_transaction_path(transaction)
          = link_to 'Delete', transaction_path(transaction), method: :delete
        
br
= link_to 'New', new_transaction_path

app/views/transactions/new.html.slim
h1 
  | New Transactions 
= render 'form', transaction: @transaction
= link_to 'Back', transactions_path, class: "btn btn-sm fw-bold btn-secondary me-2 mb-2"

app/views/transactions/show.html.slim
p#notice 
  = notice 
p 
  strog 
    | Type 
  = @transaction.transaction_type
p 
  strog 
    | Value
  = @transaction.value
p 
  strog 
    | Description 
  = @transaction.description
p 
  strog 
    | Transaction Date 
  = @transaction.transaction_date
p 
  strog 
    | Status
  = @transaction.status
p
= link_to 'Edit', edit_transaction_path(@transaction)
= link_to 'Delete', transaction_path(@transaction), method: :delete
= link_to 'Back', transactions_path